ALTER TABLE "contact_messages" ADD CONSTRAINT "contact_messages_subject_check" CHECK ("contact_messages"."subject" in ('general','emergency','follow_up','complaint','other'));--> statement-breakpoint
ALTER TABLE "contact_status_history" ADD CONSTRAINT "contact_status_history_previous_check" CHECK ("contact_status_history"."previous_status" is null or "contact_status_history"."previous_status" in ('new','read','in_progress','replied','closed','archived','spam'));--> statement-breakpoint
ALTER TABLE "contact_status_history" ADD CONSTRAINT "contact_status_history_new_check" CHECK ("contact_status_history"."new_status" in ('new','read','in_progress','replied','closed','archived','spam'));--> statement-breakpoint
ALTER TABLE "quote_attachments" ADD CONSTRAINT "quote_attachments_size_check" CHECK ("quote_attachments"."size_bytes" > 0 and "quote_attachments"."size_bytes" <= 10485760);--> statement-breakpoint
ALTER TABLE "quote_attachments" ADD CONSTRAINT "quote_attachments_mime_check" CHECK ("quote_attachments"."mime_type" in ('image/png','image/jpeg','image/webp','application/pdf'));--> statement-breakpoint
ALTER TABLE "quote_requests" ADD CONSTRAINT "quote_requests_intervention_check" CHECK ("quote_requests"."intervention_type" in ('refection','fuite','demoussage','gouttieres','isolation','velux','autre'));--> statement-breakpoint
ALTER TABLE "quote_requests" ADD CONSTRAINT "quote_requests_roof_check" CHECK ("quote_requests"."roof_type" in ('ardoise','tuile_terre_cuite','tuile_beton','zinc','bac_acier','je_ne_sais_pas'));--> statement-breakpoint
ALTER TABLE "quote_requests" ADD CONSTRAINT "quote_requests_surface_check" CHECK ("quote_requests"."surface" in ('less_50','50-100','100-150','more_150','unknown'));--> statement-breakpoint
ALTER TABLE "quote_status_history" ADD CONSTRAINT "quote_status_history_previous_check" CHECK ("quote_status_history"."previous_status" is null or "quote_status_history"."previous_status" in ('draft','submitted','under_review','contacted','visit_scheduled','estimate_in_preparation','estimate_sent','accepted','rejected','cancelled','archived'));--> statement-breakpoint
ALTER TABLE "quote_status_history" ADD CONSTRAINT "quote_status_history_new_check" CHECK ("quote_status_history"."new_status" in ('draft','submitted','under_review','contacted','visit_scheduled','estimate_in_preparation','estimate_sent','accepted','rejected','cancelled','archived'));